CreationDate = 2022-11-20T13:50:27.969661

[cam_0]
port = 0
resolution = [ 640, 480,]
rotation_count = 0
error = 0.624
camera_matrix = [ [ "390.79054869572275", "0.0", "329.61660876641224",], [ "0.0", "397.875188570515", "225.4669979883386",], [ "0.0", "0.0", "1.0",],]
distortion = [ [ "0.04900463256589997", "0.1635475806405021", "0.022334350522460293", "0.00888425616010655", "-0.37283043601933696",],]
exposure = -6.0
grid_count = 24
ignore = false

[cam_1]
port = 1
resolution = [ 640, 480,]
rotation_count = 0
error = 0.375
camera_matrix = [ [ "828.3334828818445", "0.0", "325.82429699310615",], [ "0.0", "832.1154402153408", "228.91866643752184",], [ "0.0", "0.0", "1.0",],]
distortion = [ [ "0.07887937888179357", "-1.4194072740180295", "0.00019555687892045188", "0.0040257687741203215", "8.765188003477647",],]
exposure = -7.0
grid_count = 29
ignore = false

[cam_2]
port = 2
resolution = [ 640, 480,]
rotation_count = 0
error = 0.954
camera_matrix = [ [ "451.9246006839845", "0.0", "325.6912194045046",], [ "0.0", "456.8808325839037", "196.99812977819514",], [ "0.0", "0.0", "1.0",],]
distortion = [ [ "0.2998718437520085", "-0.47323462852405884", "-0.04117829354912019", "0.001685066684725389", "0.36504413313324374",],]
exposure = -6.0
grid_count = 44
ignore = false

[charuco]
columns = 4
rows = 5
board_height = 11.0
board_width = 8.5
dictionary = "DICT_4X4_1000"
units = "inch"
aruco_scale = 0.75
square_size_overide_cm = 5.25
inverted = true

[stereo_0_1]
grid_count = 43
rotation = [ [ "0.9852151031654297", "0.08096917609769047", "0.1509807703543501",], [ "-0.12847637378272136", "0.9321718535616454", "0.3384515575486227",], [ "-0.11333588078968759", "-0.3528450480728154", "0.9287924150078521",],]
translation = [ [ "0.21021926198492408",], [ "-0.38661830619282184",], [ "0.26426621357090296",],]
RMSE = 1.8362587271730282

[stereo_0_2]
grid_count = 44
rotation = [ [ "0.8505163894584903", "-0.09775448854778214", "-0.5167842211515897",], [ "0.04310017343151186", "0.9922251177090593", "-0.11675483218015856",], [ "0.5241795935675743", "0.07702840875939812", "0.8481169600540528",],]
translation = [ [ "0.5107955368245444",], [ "-0.13027313419149272",], [ "0.34788375031295343",],]
RMSE = 1.6070834614921825

[stereo_1_2]
grid_count = 43
rotation = [ [ "0.7684983839941949", "-0.3724164946655305", "-0.5203039383853921",], [ "0.11444208073005355", "0.8800527178540979", "-0.4608798367858933",], [ "0.6295341483640796", "0.2946407444646014", "0.7189392100482895",],]
translation = [ [ "0.31142932370057874",], [ "0.3021593968355123",], [ "0.16089351031047996",],]
RMSE = 1.3123444560015116
