[tool.poetry]
name = "pyxy3d"
version = "0.3.2"
description = "GUI based multicamera calibration that integrates with 2D landmark tracking to triangulate 3D landmark positions"
authors = ["Mac Prible <prible@gmail.com>"]
license = "LGPL-3.0-only"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
pandas = "^1.5.0"
scipy = "^1.10.1"
pyqtgraph = "^0.13.2"
PyOpenGL = "^3.1.6"
toml = "^0.10.2"
numba = "^0.57.0"
mediapipe = "0.10.1"
pyside6 = "^6.5.2"
pyqtdarktheme = "^2.1.0"
opencv-contrib-python = "^4.8.0.74"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pytest = "^7.3.0"
ipykernel = "^6.22.0"
pymdown-extensions = ">=9.11,<11.0"
mkdocs-material = "^9.1.6"
mkdocs-git-revision-date-localized-plugin = "^1.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
repository = "https://github.com/mprib/pyxy3d"

[tool.poetry.scripts]
pyxy3d = "pyxy3d.__main__:CLI_parser"

[tool.setuptools_scm]
write_to = "pyxy3d/_version.py"