[tool.poetry]
name = "pyxy3d"
version = "0.0.20"
description = "A package for calibrating standard webcams to enable 3d motion tracking"
authors = ["Mac Prible <prible@gmail.com>"]
license = "AGPL-3.0-only"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
opencv-contrib-python = "^4.7"
PyQt6 = "^6.4.0"
pandas = "^1.5.0"
scipy = "^1.10.1"
mediapipe = "^0.9.2.1"
pyqtgraph = "^0.13.2"
PyOpenGL = "^3.1.6"
toml = "^0.10.2"
numba = "^0.56.4"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pytest = "^7.3.0"
ipykernel = "^6.22.0"
pymdown-extensions = ">=9.11,<11.0"
mkdocs-material = "^9.1.6"
mkdocs-git-revision-date-localized-plugin = "^1.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
repository = "https://github.com/mprib/pyxy3d"

[tool.poetry.scripts]
pyxy3d = "pyxy3d.__main__:CLI_parser"