[tool.poetry]
name = "caliscope"
version = "0.5.4"
description = "GUI based multicamera calibration that integrates with 2D landmark tracking to triangulate 3D landmark positions"
authors = ["Mac Prible <prible@gmail.com>"]
license = "BSD-2-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.13"
pandas = "^1.5.0"
scipy = "^1.10.1"
pyqtgraph = "^0.13.2"
PyOpenGL = "^3.1.6"
numba = "^0.57.0"
mediapipe = "0.10.20"
pyside6 = "^6.5.2"
opencv-contrib-python = "^4.8.0.74"
rtoml = "^0.9.0"
pyarrow = "^15.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.0"
ipykernel = "^6.22.0"
pymdown-extensions = ">=9.11,<11.0"
mkdocs-material = "^9.1.6"
mkdocs-git-revision-date-localized-plugin = "^1.2.0"
ruff = "^0.6.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
repository = "https://github.com/mprib/caliscope"

[tool.poetry.scripts]
caliscope = "caliscope.__main__:CLI_parser"

[tool.setuptools_scm]
write_to = "caliscope/_version.py"


[tool.ruff]
lint.select = ["E", "F", "W","I"]
lint.ignore = []
unsafe-fixes = true

# Allow autofix for all enabled rules (when `--fix`) is provided.
lint.fixable = ["E", "F", "W","I"]
# lint.fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
lint.unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "dev",
]

line-length = 120

# Allow unused variables when underscore-prefixed.
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10.
target-version = "py310"

[tool.ruff.format]



[tool.ruff.lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10