CreationDate = 2022-11-06T08:35:07.129308
stereo_0_2_RMSE = 2.4736680116553185
stereo_0_2_rotation = [ [ "-0.9883669814599936", "-0.07354221427304776", "-0.13312495137831146",], [ "-0.024257367018954073", "0.9403381060250016", "-0.3393756421763645",], [ "0.15014090083973927", "-0.33219841823393614", "-0.9311830758867465",],]
stereo_0_2_translation = [ [ "9.849326675323791",], [ "4.959753443172465",], [ "89.27934126419756",],]
stereo_1_0_RMSE = 1.3774085657285915
stereo_1_0_rotation = [ [ "0.9962496552184935", "-0.025334477573856616", "-0.08273323832107926",], [ "0.033965025068315814", "0.9939303416796892", "0.10463676677251124",], [ "0.0795801580115384", "-0.10705437933385065", "0.9910632463754786",],]
stereo_1_0_translation = [ [ "38.79013662346197",], [ "0.7493626755453733",], [ "1.6199767079827483",],]
stereo_1_2_RMSE = 1.5690255574098422
stereo_1_2_rotation = [ [ "-0.9984766172808259", "-0.024747038920370695", "-0.04931560410369746",], [ "-0.011919200303334909", "0.9694150258250669", "-0.24513759476814923",], [ "0.05387371722433811", "-0.2441763538290676", "-0.9682332006408239",],]
stereo_1_2_translation = [ [ "-29.26142300755064",], [ "5.379980661472007",], [ "93.04453728111655",],]

[cam_0]
port = 0
resolution = [ 640, 480,]
rotation_count = 0
exposure = -6.0

[cam_1]
port = 1
resolution = [ 1024, 576,]
rotation_count = 0
error = 0.686
camera_matrix = [ [ "1141.8046368446408", "0.0", "460.4075877351642",], [ "0.0", "1158.5362532516203", "240.2111275118159",], [ "0.0", "0.0", "1.0",],]
distortion = [ [ "-0.047154385553736966", "0.6290324553832762", "-0.003878619922179416", "-0.018620515886610733", "-1.8136386786600593",],]
exposure = -5
grid_count = 37

[cam_2]
port = 2
resolution = [ 1280, 720,]
rotation_count = 0
error = 0.492
camera_matrix = [ [ "643.6068828471597", "0.0", "654.3016526321692",], [ "0.0", "643.5658323416898", "338.0713038637058",], [ "0.0", "0.0", "1.0",],]
distortion = [ [ "0.15881873544618838", "-0.2088539117513703", "0.001981018072943025", "0.0010123111059507166", "0.08968777478152505",],]
exposure = -6.0
grid_count = 83

[charuco]
columns = 4
rows = 5
board_height = 11.0
board_width = 8.5
dictionary = "DICT_4X4_1000"
units = "inch"
aruco_scale = 0.75
square_size_overide = 5.25
inverted = true
