CreationDate = 2022-12-22T10:43:16.354534

[cam_0]
port = 0
resolution = [ 1920, 1080,]
rotation_count = 0
exposure = -5.0
ignore = false
verified_resolutions = [ [ 640, 480,], [ 1280, 720,], [ 1920, 1080,],]

[cam_1]
port = 1
resolution = [ 1280, 960,]
rotation_count = 0
exposure = -7.0
ignore = false
verified_resolutions = [ [ 640, 480,], [ 1280, 720,],]

[cam_2]
port = 2
resolution = [ 1920, 1080,]
rotation_count = 0
exposure = -7.0
ignore = false
verified_resolutions = [ [ 640, 480,], [ 1280, 720,], [ 1920, 1080,],]

[cam_3]
port = 3
resolution = [ 1920, 1080,]
rotation_count = 0
exposure = -6.0
ignore = false
verified_resolutions = [ [ 640, 480,], [ 1280, 720,], [ 1920, 1080,],]

[cam_4]
port = 4
resolution = [ 1920, 1080,]
rotation_count = 0
exposure = -9.0
ignore = false
verified_resolutions = [ [ 640, 480,], [ 1280, 720,], [ 1920, 1080,],]

[charuco]
columns = 4
rows = 5
board_height = 11.0
board_width = 8.5
dictionary = "DICT_4X4_1000"
units = "inch"
aruco_scale = 0.75
square_size_overide_cm = 5.25
inverted = true
